events {}

http {
    server {
        listen 80;
        add_header Access-Control-Allow-Origin "http://localhost:4200" always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

        if ($request_method = OPTIONS) {
            return 204;
        }
        # -------------------------
        # Auth Service
        # /auth/login  -> /login
        # /auth/signup -> /signup
        # -------------------------
        location /auth/ {
            proxy_pass http://auth-service:8081/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # -------------------------
        # Trading Service
        # /trading/orders    -> /api/orders
        # /trading/portfolio -> /api/portfolio
        # -------------------------
        location /trading/ {
            proxy_pass http://trading-service:8082/api/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # -------------------------
        # Market Service
        # /market/quote/INFY
        # -> /api/market/quote/INFY
        # -------------------------
        location /market/ {
            proxy_pass http://market-service:8083/api/market/;

            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /health {
            return 200 '{"service":"gateway","status":"healthy"}';
            add_header Content-Type application/json;
        }
    }
}