apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-service
  namespace: market-platform
spec:
  replicas: 1

  selector:
    matchLabels:
      app: trading-service

  template:
    metadata:
      labels:
        app: trading-service

    spec:
      containers:
        - name: trading-service
          image: docker-trading-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8082

          envFrom:
            - secretRef:
                name: trading-service-secrets

          env:
            - name: MARKET_SERVICE_URL
              value: "http://market-service:8083"

            - name: PORT
              value: "8082"

          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
  namespace: market-platform
spec:
  selector:
    app: trading-service

  ports:
    - port: 8082
      targetPort: 8082

  type: ClusterIP
